class AvatarProducerPageLocators:
    producer_navbar = "xpath=//a[text()='Producer']"
    producer_updateagency_btn = "xpath=//button[text()='Update Agency']"
    producer_addagency_btn = "xpath=//button[contains(text(),'Add Agency')]"
    producer_searchagency_btn = "xpath=//button[contains(text(),'Search Agency')]"
    producer_saveagency = "xpath=//button[text()='Save Agency']"
    producer_add_agencycode = "xpath=//input[@id = 's_PersonUniqueId']"
    producer_search_verify_agencycode = "xpath=//input[@value='<<replace_header>>']"
    producer_add_policyproduct = "xpath=//th[text()='POLICY PRODUCT']//following::select[1]"
    producer_add_commgroup = "xpath=//th[text()='COMM.GROUP']//following::select[2]"
    producer_add_addrow = "xpath=//div[contains(@class,'modal-dialog')]//button//span[text()='Add Row']"
    producer_agency_visit_review = "xpath=//button[text()='Agency Visit Review']"
    producer_agency_visit_date ="xpath=//input[@id='d_AgencyVisitDate']"
    producer_agency_addlog = "xpath=//span[text()='Add Log']"
    producer_agency_previsit_note = "xpath=//textarea[@id='s_PreVisitNote']"
    producer_agency_staff_note = "xpath=//textarea[@id='s_StaffNotes']"
    producer_agency_agent_requests = "xpath=//textarea[@id='s_AgentRequests']"
    producer_agency_visit_notes = "xpath=//textarea[@id='s_VisitReviewNotes']"
    producer_agency_submit = "xpath=//button[text()=' Submit']"
    producer_agency_close = "xpath=//button[@class='close']/span"
    producer_agency_close_main = "xpath=//button[@class='close']/span"
    producer_add_buttonclose = "xpath=//button[text()='CLOSE']"
    producer_add_agencyname = "xpath=//input[@id = 's_LastOrganizationName']"
    producer_add_selectgrup = "xpath=//select[@id = 'doc_n_docgroupId_FK']"
    producer_add_uv = "xpath=//select[@id = 'role_n_UWAssigned']"
    producer_add_payeename = "xpath=//input[@id = 's_PayeeName']"
    producer_add_agencystatus = "xpath=//select[@id = 's_PersonStatusCode']"
    producer_add_dbaname = "xpath=//input[@id = 's_DBAName']"
    producer_add_feinnuber = "xpath=//input[@id = 's_SSNNo']"
    producer_add_servicerep = "xpath=//select[@id = 'role_n_ServiceRep']"
    producer_add_mailingaddress = "xpath=//input[@id = 'mail_s_AddressLine1']"
    producer_add_zip = "xpath=//input[@id='mail_s_PostalCode']"
    producer_add_selectzip = "xpath=//div[@class='modal-body']//div[@class='row']//a[text()='EMPIRE STATE']"
    producer_add_mailingzip = "xpath=//input[@id = 'mail_s_PostalCode']"
    prducer_add_checkbox = "xpath=//span[@class='switch-slider']"
    producer_add_bankacc = "xpath=//input[@id ='acc_s_BankAccountNO']"
    producer_add_bankname = "xpath=//input[@id ='acc_s_BankName']"
    producer_add_routingno = "xpath=//input[@id ='acc_s_RoutingNO']"
    producer_add_locationaddress = "xpath=//input[@id = 'loc_s_AddressLine1']"
    producer_add_locationzip = "xpath=//input[@id = 'loc_s_PostalCode']"
    producer_add_web = "xpath=//input[@id = 'web_s_WebsiteURL']"
    producer_add_phone = "xpath=//input[@id = 'phone_s_PhoneNumber']"
    producer_add_fax = "xpath=//input[@id = 'fax_s_FaxNumber']"
    producer_add_directdeposit = "xpath=//select[@id = 'acc_n_AccountCode1']"
    producer_add_manager= "xpath=//input[@id = 'manager_s_FirstName']"
    producer_add_managerphone = "xpath=//input[@id = 'manager_s_PhoneNumber']"
    producer_add_manageremail = "xpath=//input[@id = 'manager_s_EmailAddress']"
    producer_add_principal = "xpath=//input[@id = 'contact_s_ContactName']"
    producer_addrow_license = "xpath=//span[text()='Add Row']"
    producer_add_licensetype = "xpath=//th[text()='LICENSE TYPE']//following::select[1]"
    producer_add_licenseno = "xpath=//th[text()='LICENSE TYPE']//following::input[1]"
    producer_add_state = "xpath=//th[text()='LICENSE TYPE']//following::select[2]"
    producer_add_appointed = "xpath=//th[text()='LICENSE TYPE']//following::select[3]"
    producer_add_issuedate = "xpath=//th[text()='LICENSE TYPE']//following::input[2]"
    producer_add_expdate = "xpath=//th[text()='LICENSE TYPE']//following::input[3]"
    producer_add_appdate = "xpath=//th[text()='LICENSE TYPE']//following::input[4]"
    producer_add_principalphone ="xpath=//input[@id = 'contact_s_PhoneNumber']"
    producer_add_principalemail = "xpath=//input[@id = 'contact_s_Email']"
    #producer_add_addrow= "xpath=//button[@type = 'button']//preceding::span[text()='Add Row']"
    producer_add_saveagency = "xpath=//button[text()='Save Agency']"
    producer_licenseinformation_grid ="xpath=//strong[text()='License Information']/../..//table/tbody/tr/td[count(//table/thead/tr/th[.='<<header_replace>>']/preceding-sibling::th)+1]"
    producer_search_agencycode = "xpath=//input[@id = 'clientId']"
    producer_search_agencyname = "xpath=//input[@id = 'lastOrg']"
    producer_search_feinnumber = "xpath=//input[@id = 'feinNumber']"
    producer_search_dbaname = "xpath=//input[@id ='dbaName']"
    producer_search_zip = "xpath=//input[@id='zip']"
    producer_search_county = "xpath=//input[@id='county']"
    producer_search_state = "xpath=//input[@id='state']"
    producer_search_city = "xpath=//input[@id='city']"
    producer_search_principalname = "xpath=//input[@id='principalName']"
    producer_search_managername = "xpath=//input[@id='managerName']"
    producer_search_license = "xpath=//input[@id='license']"

    producer_search_searchbtn = "xpath=//button[text()=' Search']"
    producer_select_agencycode = "xpath=//table[@class='table table-striped table-bordered table-hover']//tbody//tr//td[1]//a[text()='<<header_replace>>']"
    producer_agencyusers_button="xpath=//button[text()='Agency Users']"
    producer_documents_button="xpath=//button[text()='Documents']"
    producer_document_file_name = "xpath=//input[@id='s_UserFileName']"
    producer_document_file_type = "xpath=//select[@id='n_docfileId_FK']"
    producer_document_file = "xpath=//input[@id='fileDocument']"
    producer_document_submit = "xpath=//button[contains(text(),'Submit')]"
    producer_document_close = "xpath=//button[text()='CLOSE']"
    producer_commisson_button="xpath=//button[text()='Commission']"
    producer_updatedlogs_button="xpath=//button[text()='Updated Logs']"
    producer_agencyvisitreview_button="xpath=//button[text()='Agency Visit Review']"
    producer_products_button="xpath=//button[text()='Products']"
    # AGENCY USER FORM
    producer_agencyuserform_userid = "id=Username"
    producer_agencyuserform_subagentid = "id=Sub_Agent_ID"
    producer_agencyuserform_firstname = "id=First_Name"
    producer_agencyuserform_middlename = "id=s_MiddleName"
    producer_agencyuserform_lastname = "id=Last_Name"
    producer_agencyuserform_screenname = "id=s_ScreenName"
    producer_agencyuserform_email = "id=Email"
    producer_agencyuserform_phonenumber = "id=s_PhoneNumber"
    producer_agencyuserform_userstatus = "id=s_UserStatus"
    producer_agencyuserform_userlevel= "id=Level"
    producer_agencyuserform_efffrom= "id=d_EffectiveDate"
    producer_agencyuserform_effto = "id=d_ExpiryDate"
    producer_agencyuserform_addrow = "xpath=//strong[text()='UserProducts']//..//button//span[text()='Add Row']"
    producer_agency_product = "id=n_Product_FK"
    producer_agency_state = "id=s_StateCode"
    producer_agency_representative = "id=n_ServiceRep"
    producer_agency_uvassign = "id=n_UWAssigned"
    producer_agency_license = "xpath=//select[@id='n_UWAssigned']//following::input"
    producer_agency_authorization = "xpath=//select[@id='n_UWAssigned']//following::select"
    producer_agency_save_agency = "xpath=//span[text()='Save Agency User']"
    producer_agency_user_close ="xpath=//button[text()='CLOSE']"
    producer_agencyuserform_userproducts_grid ="xpath=//strong[text()='License Information']/../..//table/tbody/tr/td[count(//table/thead/tr/th[.='<<header_replace>>']/preceding-sibling::th)+1]"
    producer_update_log_value = "xpath=//h5[text()='Updated Logs']/following::table[2]/tbody/tr[1]/td[contains(text(), '<<header_replace>>')]"

#--------------------new doc locatores------------------------------
    producer_doc_filename = "xpath=//input[@id='fileName']"
    producer_doc_doctype = "xpath=//div[@id= 'Doctype_Name_DD1']"
    producer_doc_description = "xpath=//textarea[@id= 'description']"
    producer_doc_uploaddate = "xpath=//input[@name='uploadDate]'"
    producer_dragdrop_file = "xpath=//input[@class= 'FileInput']"
    producer_doc_uploadbtn = "xpath=//button[contains(text(),'Upload')]"
    producer_doc_closebtn = "xpath=//button[contains(text(),'CLOSE')]"
    producer_doc_selectdoctype = "xpath=//div[text()='Acknowledgement Letter']"










