class AvatarCreateQuoteLocators:

    policy_createquote = "xpath=//a[text()='Create Quote/Bind']"
    policy_ho3_homeowners = "xpath=//span[text()='HO3 Homeowners']"
    policy_ho6_homeowners = "xpath=//span[text()='HO6 Homeowners']"
    policy_mdp_direct = "xpath=//span[text()='MDP Direct']"
    policy_mho_direct = "xpath=//span[text()='MHO Direct']"
    policy_commercial_program = "xpath=//span[text()='Commercial Program']"
    policy_cnr = "xpath=//span[text()='CNR']"
    policy_ho3_diamond = "xpath=//span[text()='HO3 Diamond']"
    policy_elements_ho3_select = "xpath=//span[text()='Elements HO3 Select']"
    policy_elements_ho6_select = "xpath=//span[text()='Elements HO6 Select']"
    policy_tab = "xpath=//a[text()='Policy']"

#------HO3 Homeowners locators--------------------------------------------------
    policy_application_information = "xpath=//span[text()='Applicant Information']"
    policy_firstname = "xpath=//input[@id='s_FirstName']"
    policy_lastname = "xpath=//input[@id='s_LastOrganizationName']"
    policy_dob = "xpath=//input[@id='d_BirthDate']"
    policy_occupation = "xpath=//input[@id='s_OccupationDes']"
    policy_house_no = "xpath=//input[@id='s_HouseNo']"
    policy_streetname = "xpath=//input[@id='s_StreetName']"
    policy_postalcode = "xpath=//input[@id='s_PostalCode']"
    policy_propertydetails = "xpath=//span[text()='Property Details']"
    policy_ppc = "xpath=//select[@name='data[PROTECTIONCLS]']"
    policy_bceg = "xpath=//select[@name='data[HOBCEGCODE]']"
    policy_constrcution_type = "xpath=//select[@name='data[CONSTRTYPE]']"
    policy_coverages_tab = "xpath=//span[text()='Coverages']"
    policy_deductibles_tab = "xpath=//span[text()='Deductible']"
    policy_yearbuilt = "xpath=//input[@name='data[yearbuilt]']"
    policy_dwelling= "xpath=//input[@id='txt_basicCVG_1']"
    policy_rate = "xpath=//span[text()='Claim Question']//following::button[@name='Ratesubmit']"
    policy_errors = "xpath=//h5[text()='Errors']"
    policy_cancel = "xpath=//button[text()='Cancel']"
    policy_select_city = "xpath=//h5[text()='Select City']"
    policy_city = "xpath=//a[text()='FORT LAUDERDALE']"
    policy_personal_property = "xpath=//input[@id='txt_basicCVG_1']"
    policy_personal_liability = "xpath=//select[@name='dd_basicCVG_5']"
    policy_medical_payments = "xpath=//select[@name='dd_basicCVG_6']"
    policy_nonhurricane = "xpath=//select[@name='ddDeductNonHurricane']"
    policy_hurricane = "xpath=//select[@name='ddDeductHurricane']"
    policy_covergae_limit = "xpath=//select[@id='HOMOLDCVG']"
    policy_coverage_limit2 = "xpath=//select[@id='HOMOLDCVGLIX']"
    policy_roof_type = "xpath=//select[@name='data[ROOFTYPE]']"
    policy_roof_subtype = "xpath=//select[@name='data[ROOFSUBTYPE]']"
    policy_error_in_text = "xpath=//strong/li[contains(text(),'<<replace_header>>')]"
    policy_structure_type = "xpath=//select[@id='data[STRUCTYPE]']"
    policy_nor = "xpath=//input[@name='data[TbPoriskadditionalinfo][n_NoOfResidents]']"
    policy_area_sqft = "xpath=//input[@name='data[TbPoriskadditionalinfo][n_HomeSqft]']"
    policy_occupancy_type= "xpath=//select[@name='data[OCCUPYTYPE]']"
    policy_firestn = "xpath=//input[@name='data[TbPoriskadditionalinfo][n_DistanceFireStation]']"
    policy_hydrant = "xpath=//input[@name='data[TbPoriskadditionalinfo][n_DistanceHydrant]']"
    policy_premium_value ="xpath=//span[contains(text(),'Premium')]/following::span"






