class AvatarClaimIntakePageLocaters:

    claimview_tab = "xpath=//a[text()='Claim view']"
    claimtype_selectbox = "id=ClaimType_txt"
    typeofloss_selectbox = "id=TypeofLoss"
    servicerep_selectbox = "id=ServiceRep"
    eventname_selectbox = "id=Event_Name"
    claimstatusopen_dropdown = "id=status_txt"
    claimsubstatus ="xpath=//select[@id='substatus_txt']"
    updatecliam_btn = "xpath=//button[text()='UPDATE CLAIM']"
    saveclaim_btn = "xpath=//button[text()='SAVE CLAIM']"
    location_selectbox = "xpath=//select[@name='PORiskMaster_PK']"
    primaryphonenumber_textbox = "id=PrPhoneNum"
    secondaryphonenumber_textbox= "id=SePhoneNum"
    emailaddress_textbox = "id=emailAddress"
    dateloss_textbox = "xpath=//input[@name='claimDetails.date_of_loss']"
    painvolved_checkbox = "xpath=//input[@name='claimDetails.PAInvolved']"
    attorneyinvolved_checkbox = "xpath=//input[@name='claimDetails.AttorneyInvolved']"
    aobinvolved_checkbox = "xpath=//input[@name='claimDetails.AOBInvolved']"
    claimreportedtype_selectbox = "id=relationType_txt"
    primaryattorneyassigned_selectbox = "id=PrimaryAttorney_PK"
    coattorneyassigned_selectbox = "id=CoAttorney_PK"
    inhousecouncel_selectbox = "id=In_House_Counsel"
    dfscomplaint_checkbox = "xpath=//input[@name='claimDetails.DFSComplain']"
    claimreviewstatus_selectbox ="id=claim_review_status"
    claimsubstatus_selectbox = "id=substatus_txt"
    claimapproved_radio_yes = "xpath=//input[@name='claim_approved' and @value='Y']"
    claimapproved_radio_no = "xpath=//input[@name='claim_approved' and @value='N']"
    totalloss_radio = "id=totalLoss"
    rightotrepair_radio = "id=rightToRepair"
    saveclaim_btn = "xpath=//button[text()='SAVE CLAIM']"
    payments_button = "xpath=//li[@class='nav-item']//a[text()='Payments']"
    payments_transactiontype_selectbox = "xpath=//label[text()='Transaction Type']/../following-sibling::td/select"
    payments_transactionsubtype_selectbox = "xpath=//label[text()='Transaction Sub Type']/../following-sibling::td/select"
    payments_date_inputdatebox1 = "xpath=//label[text()='Date']/../following-sibling::td/input"
    payments_date_inputdatebox ="xpath=//input[@name = 'reservePayment.dateReserves']"
    payments_description_textarea = "xpath=//label[text()='Description']/../following-sibling::td/textarea"
    payments_refund_checkbox = "xpath=//td[text()='Refund']//following-sibling::td//inputs"
    payments_refundcheck_checkbox = "xpath=//td[text()='Refund Check']//following-sibling::td//input"
    payments_claim_deductible_button ="xpath=//button[text()='Claim Deductible Payment']"
    attachments_button = "xpath=//li[@class='nav-item']//a[text()='Attachments']"
    attachments_add_attachment = "xpath=//button[text()='Add Attachments']"
    attachments_filename_textbox = "xpath=//td[text()='File Name']/../td/input"
    attachments_authorisation_selectbox ="xpath=//td[text()='Authorisation']/../td/select"
    attachments_attachmenttype_selectbox = "xpath=//td[text()='Attachment Type']/../td/select"
    attachments_documenttype_selectbox = "xpath=//td[text()='Document Type']/../td/select[contains(@class,'height')]"
    attachments_description_textarea = "xpath=//td[text()='Description']/../following-sibling::tr/td/textarea"
    attachments_documentattach_inputfile="xpath=(//td[text()='Document Attach']//../following-sibling::tr/td/input)[1]"
  #  assoparty_activity_selectBox =
    add_info_totalestimate = "xpath=//*[text()='Total Estimate']//following::input[1]"
    add_info_releaseamount = "xpath=//*[text()='GR Release Amount']//following::input[1]"
    add_infotab = "xpath=//*[text()='Add. Info']"
    add_info_update = "xpath=//button[text()='Update']"

    asso_party_tab = "xpath=//a[text()='Asso. Party']"
    asso_party_addrow = "xpath=//button[text()='Add Row']"

    payment_nameoncheck = "xpath=//input[@id='PayeeName']"
    payment_invoicedate = "xpath=//input[@id='InvoiceDate']"
    payment_invoiceduedate = "xpath=//input[@id='InvoiceDueDate']"
    payment_invoice = "xpath=//input[@id='InvoiceNo']"




